name = "creator-finder"
main = "src/index.tsx"
compatibility_date = "2024-10-20"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false
upload_source_maps = true
assets = { directory = "./public/" }

[vars]
ORIGIN = ['https://creator-finder.abdulisik.com', 'http://localhost:8787']
PAGE_SIZE = 20
DELAY_SECONDS = [61, 301, 3601, 43200, 43200, 43200, 43200] # 1 minute, 5 minutes, 1 hour, 12 hours...

[[d1_databases]]
binding = "DB"
database_name = "creator_finder_db"
database_id = "b63bac41-54e0-4c8e-8701-38c3b3b208fb"

[[queues.producers]]
  queue = "creator-finder-links"
  binding = "LINK_QUEUE"

[[queues.consumers]]
  queue = "creator-finder-links"
  dead_letter_queue = "creator-finder-links-dead"
  max_batch_size = 100
  max_batch_timeout = 10
  max_retries = 5
  retry_delay = 90

[observability]
enabled = true
head_sampling_rate = 1

[[unsafe.bindings]]
name = "LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }