name = "creator-finder"
main = "src/index.tsx"
compatibility_date = "2024-10-20"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "creator_finder_db"
database_id = "b63bac41-54e0-4c8e-8701-38c3b3b208fb"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1