name = "creator-finder"
main = "src/index.tsx"
compatibility_date = "2024-10-20"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false
upload_source_maps = true
assets = { directory = "./public/" }

[[d1_databases]]
binding = "DB"
database_name = "creator_finder_db"
database_id = "b63bac41-54e0-4c8e-8701-38c3b3b208fb"

[observability]
enabled = true
head_sampling_rate = 1

[[unsafe.bindings]]
name = "LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }